### PR TITLE
Selectable Soundpack

### LINKED ISSUE #1: [Feature Request] Selectable Soundpack
Hello! In the latest Hikaru stream, he did mention how can we expand this extension with a sound pack. I was thinking that we can replace the dropdown with checkboxes to select sound packs of chess players we like, so more sounds can be added in the future. I also could work on this feature if you want.

(Also, Levy was saying more voice lines in his stream which we can also add them later.)

### PR DESCRIPTION
**Pull request by rootEnginear**
The checkboxes are here! It should be a good foundation for more sound packs added later. This PR will close #1, but after I look at #10, I am afraid that there might be some styling conflict. If my code has any problems, please feel free to tell me.

### CODE REVIEW

**Comment by shuhaoli** [comment]
Nice work! I tried it out locally, for some reason when I spectate a game on chess.com, after a while the entire window freezes - have you encountered this? Would you know what might be causing this?

**Comment by rootEnginear** [comment]
It is embarrassing that I have overlooked this issue. The problem is that the sound effect pack only has one line, but the random function tried to random others number than '1'. Resulting in an infinite loop and make the page frozen. The latest commit should help :)

**Comment by shuhaoli** [comment]
Thanks for the update! One general thing I'm wondering is, what is the difference between the old .wav files and new .mp3 files that led to this conversion?
I will merge your PR after you resolve the conflicts with main. Thanks again!

**Comment by rootEnginear** [comment]
The reason is that the `.wav` audio file is uncompressed, but `.mp3` is. So it is ideal to keep the extension as small as possible, which is why I converted all audio into `.mp3`.

I have also resolved the conflicts, yet you should again review them before merging. Thank you :)

**Comment by shuhaoli** [comment]
Thanks again for the work! Do you have a preferred name for me to shout you out with?

**Comment by rootEnginear** [comment]
> Thanks again for the work! Do you have a preferred name for me to shout you out with?

rootEnginear is fine. Thanks 👍🏽

**Pull request merged**
